### ISSUE TITLE
BlocklyCoding

### ISSUE THREAD

**Issue by MiracleHcat** [JiaFeiMiao-K-Cat/PetpetGenerator#1]
Hello, may I ask how to write this auto-generating image program using the Blockly language?

**Comment by JiaFeiMiao-K-Cat** [comment]
I'm not familiar with Blockly language, so I can't give you constructive suggestions.

If you want to learn more about its working principle, you can read the code in `Petpet/Utils/PetPet.cs`, especially the Method `ProcessExtendedPetpetImage` and `ProcessPetPetImage`.

In short, the image you provided(**imgA**) is in the buttom layer, and our templates(**imgB**) is in the top layer, 
so you can see **imgA** through the transparent part of **imgB**.
